name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: Salindakrish/trigger-workflow-and-wait@V1.0
        with:
          owner: Salindakrish
          repo: test-keycloak
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: main.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
